CREATE SCHEMA IF NOT EXISTS `secoms3190` DEFAULT CHARACTER SET utf8 ;
USE `secoms3190`;

CREATE TABLE IF NOT EXISTS `secoms3190`.`menu` (
`id` INT AUTO_INCREMENT,
`name` VARCHAR(255) NOT NULL,
`calories` INT NOT NULL,
`cost` INT NOT NULL,
`category` VARCHAR(255) NOT NULL,
`servingsize` VARCHAR(255) NOT NULL,
PRIMARY KEY (`id`)
);